server:
  port: 8082

spring:
  application:
    name: order-service

# If Eureka is running, this will use discovery instead of the URL property below.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: health,info, beans


resilience4j:
  circuitbreaker:
    instances:
      productClient:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
  retry:
    instances:
      productClient:
        maxAttempts: 3
        waitDuration: 200ms
