server:
  port: 8081

spring:
  application:
    name: product-service

# If you start an Eureka server at localhost:8761, discovery will work out of the box.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info
